In [8]:
import pandas as pd
d = pd.read_csv('insurance.csv')
d.head(20)

    108  392.5
0    19   46.2
1    13   15.7
2   124  422.2
3    40  119.4
4    57  170.9
5    23   56.9
6    14   77.5
7    45  214.0
8    10   65.3
9     5   20.9
10   48  248.1
11   11   23.5
12   23   39.6
13    7   48.8
14    2    6.6
15   24  134.9
16    6   50.9
17    3    4.4
18   23  113.0
19    6   14.8

In [1]:
# Example of Simple Linear Regression on the Swedish Insurance Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt

# Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
    return dataset

# Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())

# Split a dataset into a train and test set
def train_test_split(dataset, split):
    train = list()
    train_size = split * len(dataset)
    dataset_copy = list(dataset)
    while len(train) < train_size:
        index = randrange(len(dataset_copy))
        train.append(dataset_copy.pop(index))
    return train, dataset_copy

# Calculate root mean squared error
def rmse_metric(actual, predicted):
    sum_error = 0.0
    for i in range(len(actual)):
        prediction_error = predicted[i] - actual[i]
        sum_error += (prediction_error ** 2)
    mean_error = sum_error / float(len(actual))
    return sqrt(mean_error)

# Evaluate an algorithm using a train/test split
def evaluate_algorithm(dataset, algorithm, split, *args):
    train, test = train_test_split(dataset, split)
    test_set = list()
    for row in test:
        row_copy = list(row)
        row_copy[-1] = None
        test_set.append(row_copy)
    predicted = algorithm(train, test_set, *args)
    actual = [row[-1] for row in test]
    rmse = rmse_metric(actual, predicted)
    return rmse

# Calculate the mean value of a list of numbers
def mean(values):
    return sum(values) / float(len(values))

# Calculate covariance between x and y
def covariance(x, mean_x, y, mean_y):
    covar = 0.0
    for i in range(len(x)):
        covar += (x[i] - mean_x) * (y[i] - mean_y)
    return covar

# Calculate the variance of a list of numbers
def variance(values, mean):
    return sum([(x-mean)**2 for x in values])

# Calculate coefficients
def coefficients(dataset):
    x = [row[0] for row in dataset]
    y = [row[1] for row in dataset]
    x_mean, y_mean = mean(x), mean(y)
    b1 = covariance(x, x_mean, y, y_mean) / variance(x, x_mean)
    b0 = y_mean - b1 * x_mean
    return [b0, b1]

# Simple linear regression algorithm
def simple_linear_regression(train, test):
    predictions = list()
    b0, b1 = coefficients(train)
    for row in test:
        yhat = b0 + b1 * row[0]
        predictions.append(yhat)
    return predictions

# Simple linear regression on insurance dataset
seed(1)
# load and prepare data
filename = 'insurance.csv'
dataset = load_csv(filename)
for i in range(len(dataset[0])):
    str_column_to_float(dataset, i)
# evaluate algorithm
split = 0.6
rmse = evaluate_algorithm(dataset, simple_linear_regression, split)
print('RMSE: %.3f' % (rmse))

RMSE: 33.630

In [9]:
import pandas as pd
df = pd.read_csv('Absenteeism_at_work.csv')
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,Disciplinary failure,Education,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,97,0,1,30,4
1,36,0,7,3,1,118,13,18,50,239.554,97,1,1,31,0
2,3,23,7,4,1,179,51,18,38,239.554,97,0,1,31,2
3,7,7,7,5,1,279,5,14,39,239.554,97,0,1,24,4
4,11,23,7,5,1,289,36,13,33,239.554,97,0,1,30,2

In [ ]:
	ID	Reason for absence	Month of absence	Day of the week	Seasons	Transportation expense	Distance from Residence to Work	Service time	Age	Work load Average/day	Hit target	Disciplinary failure	Education	Body mass index	Absenteeism time in hours

In [3]:
# View first 20 rows
from pandas import read_csv
filename = 'Absenteeism_at_work.csv'
#names = ['ID', 'Reason for absence', 'Month of absence', 'Day of the week', 'Seasons', 'Transportation expense', 'Distance from Residence to Work', 'Service time', 'Age','Work load Average-day','Hit target','Disciplinary failure', 'Education', 'Body mass index', 'Absenteeism time in hours']
data = read_csv(filename)#, names=names)
peek = data.head(20)
print(peek)

    ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0   11                  26                 7                3        1
1   36                   0                 7                3        1
2    3                  23                 7                4        1
3    7                   7                 7                5        1
4   11                  23                 7                5        1
5    3                  23                 7                6        1
6   10                  22                 7                6        1
7   20                  23                 7                6        1
8   14                  19                 7                2        1
9    1                  22                 7                2        1
10  20                   1                 7                2        1
11  20                   1                 7                3        1
12  20                  11                 7                4        1
13   3                  11                 7                4        1
14   3                  23                 7                4        1
15  24                  14                 7                6        1
16   3                  23                 7                6        1
17   3                  21                 7                2        1
18   6                  11                 7                5        1
19  33                  23                 8                4        1

    Transportation expense  Distance from Residence to Work  Service time  \
0                      289                               36            13
1                      118                               13            18
2                      179                               51            18
3                      279                                5            14
4                      289                               36            13
5                      179                               51            18
6                      361                               52             3
7                      260                               50            11
8                      155                               12            14
9                      235                               11            14
10                     260                               50            11
11                     260                               50            11
12                     260                               50            11
13                     179                               51            18
14                     179                               51            18
15                     246                               25            16
16                     179                               51            18
17                     179                               51            18
18                     189                               29            13
19                     248                               25            14

    Age  Work load Average/day   Hit target  Disciplinary failure  Education  \
0    33                 239.554          97                     0          1
1    50                 239.554          97                     1          1
2    38                 239.554          97                     0          1
3    39                 239.554          97                     0          1
4    33                 239.554          97                     0          1
5    38                 239.554          97                     0          1
6    28                 239.554          97                     0          1
7    36                 239.554          97                     0          1
8    34                 239.554          97                     0          1
9    37                 239.554          97                     0          3
10   36                 239.554          97                     0          1
11   36                 239.554          97                     0          1
12   36                 239.554          97                     0          1
13   38                 239.554          97                     0          1
14   38                 239.554          97                     0          1
15   41                 239.554          97                     0          1
16   38                 239.554          97                     0          1
17   38                 239.554          97                     0          1
18   33                 239.554          97                     0          1
19   47                 205.917          92                     0          1

    Body mass index  Absenteeism time in hours
0                30                          4
1                31                          0
2                31                          2
3                24                          4
4                30                          2
5                31                          2
6                27                          8
7                23                          4
8                25                         40
9                29                          8
10               23                          8
11               23                          8
12               23                          8
13               31                          1
14               31                          4
15               23                          8
16               31                          2
17               31                          8
18               25                          8
19               32                          2

In [6]:
data[:1]

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,Disciplinary failure,Education,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,97,0,1,30,4

In [1]:
# Example of Simple Linear Regression on the Swedish Insurance Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt

# Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
    return dataset

# Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())

# Split a dataset into a train and test set
def train_test_split(dataset, split):
    train = list()
    train_size = split * len(dataset)
    dataset_copy = list(dataset)
    while len(train) < train_size:
        index = randrange(len(dataset_copy))
        train.append(dataset_copy.pop(index))
    return train, dataset_copy

# Calculate root mean squared error
def rmse_metric(actual, predicted):
    sum_error = 0.0
    for i in range(len(actual)):
        prediction_error = predicted[i] - actual[i]
        sum_error += (prediction_error ** 2)
    mean_error = sum_error / float(len(actual))
    return sqrt(mean_error)

# Evaluate an algorithm using a train/test split
def evaluate_algorithm(dataset, algorithm, split, *args):
    train, test = train_test_split(dataset, split)
    test_set = list()
    for row in test:
        row_copy = list(row)
        row_copy[-1] = None
        test_set.append(row_copy)
    predicted = algorithm(train, test_set, *args)
    actual = [row[-1] for row in test]
    rmse = rmse_metric(actual, predicted)
    return rmse

# Calculate the mean value of a list of numbers
def mean(values):
    return sum(values) / float(len(values))

# Calculate covariance between x and y
def covariance(x, mean_x, y, mean_y):
    covar = 0.0
    for i in range(len(x)):
        covar += (x[i] - mean_x) * (y[i] - mean_y)
    return covar

# Calculate the variance of a list of numbers
def variance(values, mean):
    return sum([(x-mean)**2 for x in values])

# Calculate coefficients
def coefficients(dataset):
    x = [row[0] for row in dataset]
    y = [row[1] for row in dataset]
    x_mean, y_mean = mean(x), mean(y)
    b1 = covariance(x, x_mean, y, y_mean) / variance(x, x_mean)
    b0 = y_mean - b1 * x_mean
    return [b0, b1]

# Simple linear regression algorithm
def simple_linear_regression(train, test):
    predictions = list()
    b0, b1 = coefficients(train)
    for row in test:
        yhat = b0 + b1 * row[0]
        predictions.append(yhat)
    return predictions

# Simple linear regression on insurance dataset
seed(1)
# load and prepare data
filename = 'Absenteeism_at_work.csv'
dataset = load_csv(filename)
for i in range(len(dataset[0])):
    str_column_to_float(dataset, i)
# evaluate algorithm
split = 0.6
rmse = evaluate_algorithm(dataset, simple_linear_regression, split)
print('RMSE: %.3f' % (rmse))

ValueError: could not convert string to float: 'ID'